language: objective-c
before_install: sudo easy_install cpp-coveralls
xcode_project: Lua.xcodeproj
xcode_scheme: Lua
after_success:
  - find ~/Library/Developer/Xcode/DerivedData/ -name "*.gcno" -exec cp -v '{}' . \;
  - find ~/Library/Developer/Xcode/DerivedData/ -name "*.gcda" -exec cp -v '{}' . \;
  - coveralls --extension .m --include Lua
